version: '3'

services:
  abci:
    depends_on:
      - tendermint
    build:
      context: .
    volumes:
      - ./abci:/usr/src/app/abci
      - ./examples:/usr/src/app/examples
      - ./tests:/usr/src/app/tests
    environment:
      TENDERMINT_HOST: tendermint
      TENDERMINT_PORT: 46657
    command: python examples/counter.py
  tendermint:
    image: tendermint/tendermint:0.13
    volumes:
      - ./tmdata:/tendermint
    entrypoint: ''
    command: bash -c "tendermint unsafe_reset_all && tendermint --log_level debug node"
  curl-client:
    image: appropriate/curl
    command: /bin/sh -c "curl http://tendermint:46657/abci_query"
