proxy_app = "tcp://abci-4:46658"
moniker = "anonymous"
fast_sync = true
db_backend = "leveldb"
log_level = "state:debug,*:error"

[consensus]
create_empty_blocks = false

[rpc]
laddr = "tcp://0.0.0.0:46657"

# TODO peers
[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "tendermint-1:46656"
